language: objective-c

sudo: false # Enable container-based builds

before_install: brew update

install: brew install python3

before_script: python3 setup.py -q install

script:
- cd $TRAVIS_BUILD_DIR/examples/cats && ./breed.sh && clowder herd -a && ./clean.sh
- cd $TRAVIS_BUILD_DIR/examples/llvm-projects && ./breed.sh && clowder herd -a && ./clean.sh
- cd $TRAVIS_BUILD_DIR/examples/cats && ./breed.sh && clowder herd && ./clean.sh
- cd $TRAVIS_BUILD_DIR/examples/llvm-projects && ./breed.sh && clowder herd && ./clean.sh
- cd $TRAVIS_BUILD_DIR/examples/cats && ./breed.sh && clowder herd -v v0.1 && ./clean.sh
- cd $TRAVIS_BUILD_DIR/examples/llvm-projects && ./breed.sh && clowder herd -v v0.1 && ./clean.sh

branches:
  only: # whitelist
    - master

notifications:
  email: false
