language: objective-c

sudo: false # Enable container-based builds

before_install: brew update

install: brew install python3

before_script: python3 setup.py -q install

script:
- ./test/test_cats_example.sh
- ./test/test_llvm_projects_example.sh

branches:
  only: # whitelist
    - master

notifications:
  email: false
