language: objective-c

sudo: false # Enable container-based builds

before_install:
    - brew update
    - echo 'Host *' >> ~/.ssh/config
    - echo '    StrictHostKeyChecking no' >> ~/.ssh/config

install: brew install python3

before_script: python3 setup.py -q install

script:
- cd $TRAVIS_BUILD_DIR/examples/cats && ./breed.sh && clowder herd
- cd $TRAVIS_BUILD_DIR/examples/llvm-projects && ./breed.sh && clowder herd

branches:
  only: # whitelist
    - master

notifications:
  email: false
