language: c

os:
  - linux
  - osx

sudo: required
dist: trusty

env:
  matrix:
    - TARGET="test_cats_example"
    - TARGET="test_llvm_example"

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install python3; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install github-release; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y python3-setuptools; fi

before_script: sudo python3 setup.py -q install

script: scripts/${TARGET}.sh

after_success: if [ "$TRAVIS_OS_NAME" = "osx" ]; then scripts/deploy.sh; fi

branches:
  only: # whitelist
    - master

notifications:
  email: false
  slack:
    secure: G5UcsKT8xMjddtTSUPXECI3uobS5/sRn87iC+fMilbpnDK3yAGoKkyCfPK4E/kJSEPZ8hBKz3uHNzpb0DdOSsjbAItiI+RQ3Glgs86B1sg2pqB2uwVPDCyPn8XHnpYPkKxFYlG19/JG9SEDej4N3kjnB4FVBm7n38ZFWjZh7s2fOjlpPKiHz8pe3B8XYfXTyQGIr9Q2I1eHbQJOEzs4PO1j/uKC1jgwe7nZnOE3sYsfcabScEHTz4Z7s9xhRXcwvorhQYQtBS7id9Gg5E4ANhoVVs7QifazDE1EK3vWjvoFYgYKnCbXzQunB09XlymrWTJZx80JOmgALU0UPUEI8Wvt/kXQP9oxqsMEeoP7UbZvXTfmeOVlm+5f5oesp/JQeBvaPj5qnbWVzcMGqi/hev4qwNv01jQOWrzVmZazw+HgeQcuaHKprK7KLdPFQR5c6CJJtwIxwdRGLmHVTtKIVQo45mEEnjHpYOmbkmmN2VETdgRlkV8t0WdCQpXXVH7uniwa7cYzb9shpiq0o+G3uHN1eUIuia/0XIVgWRL0baN6JitEBvc032M/3UrJESStQFpMF/Nw+NXm38xp7sQWReZM1ZVIBNIR1XPnaZxuLzBhKKCYcByYz7PEF71o/SkWHhAa3EKPO+9q4zceTbWunjRlp1ycUIMyhqDlCpHM8c2Y=
